FROM debian

RUN apt-get update
RUN apt-get install -y osm2pgsql

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && osm2pgsql --create -U osm -d osm -H postgis /data/belgium-200101.osm.pbf
